### ISSUE TITLE
laravel6.0 创建的users表与本包中的补充数据代码匹配不上类似问题

### ISSUE THREAD

**Issue by freebughao** [moell-peng/laravel-layui-admin#1]
我是一个php和laravel的小白，
折腾了好一会发现补充数据时用到的表名和字段名与laravel的users表以及permission创建的表完全对应不上，而README中并未说明应该如何配置，这对我一个新入门的菜鸟来说无疑增添了很多麻烦，我无法确定是不是所有版本都是如此，希望可以做的更好。

**Comment by moell-peng** [comment]
在这个包中 ，并未使用到 users 表， 能描述详细一些吗？ 在执行数据迁移和填充之前， 一定要确保执行了 `php artisan laravel-layui-admin:install`

**Comment by freebughao** [comment]
感谢您的回复，我复现了一下我的操作流程，希望可以表述的更清楚一些
laravel new laravel 创建了新的laravel6.0项目
composer require moell/laravel-layui-admin 引入此包

php artisan laravel-layui-admin:install
![image](https://user-images.githubusercontent.com/26619816/64767863-13b78a00-d57b-11e9-8e87-b0741b7c5234.png)
并且按照README配置了auth.php 以及中间件内容

php artisan migrate
![image](https://user-images.githubusercontent.com/26619816/64768665-73fafb80-d57c-11e9-8b9b-bce23fb44d58.png)
数据库中成功创建若干表（应该是laravel的users表和permission所创建的权限表，起码表名应该是）

php artisan db:seed --class="Moell\LayuiAdmin\Database\LayuiAdminTableSeeder"
![image](https://user-images.githubusercontent.com/26619816/64768822-b91f2d80-d57c-11e9-9461-0aa79e0c338c.png)
 Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.admin_users' doesn't exist (SQL: truncate table `admin_users`)
我分析的结果应该是补充数据的脚本使用的事admin_users表而migrate得到的是users表，仔细比对发现字段等内容也是不同的，因为刚入门不久，希望可以如愿引入此包到我的项目中。
祝好。

**Comment by moell-peng** [comment]
@zhanghao-heivbody 多谢反馈， 已修复， 更新至v1.0.1即可，更新之后重新执行 `php artisan laravel-layui-admin:install` 确保生成了数据迁移即可

**Comment by freebughao** [comment]
应该先将包里的migratics发布财可以执行 
php artisan db:seed --class="Moell\LayuiAdmin\Database\LayuiAdminTableSeeder"
希望在README中添加如下命令
php artisan vendor:publish --provider="Moell\LayuiAdmin\PermissionServiceProvider" --tag="migrations"

**Comment by moell-peng** [comment]
你更新到 v1.0.1 版本就好了

**Comment by freebughao** [comment]
已更新
